"""empty message

Revision ID: 29a213bb3304
Revises: e9c8aa0f01e3
Create Date: 2022-12-13 21:10:49.869819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a213bb3304'
down_revision = 'e9c8aa0f01e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('recipient')

    # ### end Alembic commands ###
