"""empty message

Revision ID: 4321e50eb4b4
Revises: 908f8ba2095e
Create Date: 2022-12-29 14:52:21.344822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4321e50eb4b4'
down_revision = '908f8ba2095e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('userEmail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userEmail', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
