"""empty message

Revision ID: 60bb6317ab63
Revises: 8e5a774277bb
Create Date: 2022-11-25 13:09:31.016105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bb6317ab63'
down_revision = '8e5a774277bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'updatedTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('updatedTime', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
