"""empty message

Revision ID: 6a04a943fbb6
Revises: f14fa5dd27c2
Create Date: 2022-12-02 10:15:23.908371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a04a943fbb6'
down_revision = 'f14fa5dd27c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('emailCount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailCount', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
