"""empty message

Revision ID: 722f9530afa6
Revises: 33233a8cc1ea
Create Date: 2022-12-24 22:00:40.931980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722f9530afa6'
down_revision = '33233a8cc1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('unread')

    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inboxpw', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('inboxpw')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
