"""empty message

Revision ID: 738fe6677a75
Revises: b9d2a3d07022
Create Date: 2022-12-22 12:15:33.447565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738fe6677a75'
down_revision = 'b9d2a3d07022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inboxpw', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('inboxpw')

    # ### end Alembic commands ###
