"""empty message

Revision ID: 8e5a774277bb
Revises: 
Create Date: 2022-11-25 09:15:49.267444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5a774277bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'updatedTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('updatedTime', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
