"""empty message

Revision ID: 908f8ba2095e
Revises: 8f94f3740001
Create Date: 2022-12-24 22:09:13.287684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908f8ba2095e'
down_revision = '8f94f3740001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_email')
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('unread')

    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inboxpw', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('inboxpw')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread', sa.BOOLEAN(), nullable=False))

    op.create_table('_alembic_tmp_email',
    sa.Column('emailid', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.TEXT(), nullable=False),
    sa.Column('senderEmail', sa.VARCHAR(), nullable=False),
    sa.Column('dateReceived', sa.DATETIME(), nullable=False),
    sa.Column('sentimentvals', sa.BLOB(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('emailid', 'senderEmail')
    )
    # ### end Alembic commands ###
