"""empty message

Revision ID: d9a2154f9a99
Revises: 60bb6317ab63
Create Date: 2022-11-29 20:01:36.518635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a2154f9a99'
down_revision = '60bb6317ab63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'updatedTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('updatedTime', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
