"""empty message

Revision ID: e9c8aa0f01e3
Revises: 2c851da9ed85
Create Date: 2022-12-12 22:12:04.073922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c8aa0f01e3'
down_revision = '2c851da9ed85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentimentvals', sa.PickleType(), nullable=False))
        batch_op.drop_column('recipientEmails')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipientEmails', sa.BLOB(), nullable=True))
        batch_op.drop_column('sentimentvals')

    # ### end Alembic commands ###
