"""empty message

Revision ID: eb362df742e0
Revises: d9a2154f9a99
Create Date: 2022-11-29 20:02:55.151970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb362df742e0'
down_revision = 'd9a2154f9a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'updatedTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('updatedTime', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
