"""empty message

Revision ID: f14fa5dd27c2
Revises: eb362df742e0
Create Date: 2022-11-29 20:08:12.713592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14fa5dd27c2'
down_revision = 'eb362df742e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('updatedTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedTime', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
